default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: free_books_development

test:
  <<: *default
  database: free_books_test

production:
  <<: *default
  database: free_books_production
  username: free_books
  password: <%= ENV['FREE_BOOKS_DATABASE_PASSWORD'] %>
